### ISSUE TITLE
Update AI forced pitstop logic

### ISSUE THREAD

**Issue by WilliamGawlik** [ac-sim-improvement-mods/ac-rules-and-race-enhancements#24]
Need to update the AI forced pitstop logic to use the new SDK function.

---Controls if AI goes to pits or not.
---@param carIndex integer @0-based car index.
---@param value boolean? @Default value: `true`.
function physics.setAIPitStopRequest(carIndex, value) end

This will help prevent the bug that causes cars to get stuck in a pitstop loop.

**Comment by WilliamGawlik** [comment]
Updated the ai forced pitstop with the new SDK function. Needs further testing.

**Comment by ZerdNerd** [comment]
Tested just now, something still doesn't work as some cars still remain in the pit. The issue manifests in getting RPMs high yet kind-of-teleporting-back to the box.

There's no bouncing as far as I know, so that part is fixed: https://i.imgur.com/sDJNhcb.mp4

The track where this was tested is Red Bull Ring in OSRW config (35 pits instead of 24). Don't know if the OSRW or amount of cars (24+player) is the issue.

**Comment by WilliamGawlik** [comment]
What session type did you test in? Paractice, quali, race, or just a single race?

**Comment by ZerdNerd** [comment]
Quali+Race (I don't run practice). RARE on the whole time, didn't turn it off/on like I recommended on RaceDepartment.

**Comment by WilliamGawlik** [comment]
I'll check it out in a bit, but my observation after making the changes on this branch were the following:

During 3 race sessions prior to the change
- Cars get stuck in this pitstop exit loop, were car is getting teleported "back to pits" repeatedly. 
- Affected an average of 10.333 cars out of 20 over the 3 race test. 

After change
- 0 out of 20 cars get stuck in pitstop exit loop

**Comment by WilliamGawlik** [comment]
I was testing in single race format, I will try weekend sessions today.

**Comment by ZerdNerd** [comment]
After rewatching the replay of test race, I have to add that 2 cars were stuck on pit->get out->pit again loop at the end of race. As I set the race for 37 laps, one started pitting on 25th, and went on with pitting on every lap till the end, while the second one pitted on 33th (one lap down) and pitted 3 times (somehow got unstuck and crossed the line normally).

**Comment by ZerdNerd** [comment]
I'm using the latest update published on RD.

**Comment by WilliamGawlik** [comment]
Well that's the problem. I'm working on multiple features on different branches. This bugfix is on the update-ai-force-pitstop branch.

**Comment by ZerdNerd** [comment]
Oh okay, sorry for causing unnecessary problems! Will try the branch then.

**Comment by WilliamGawlik** [comment]
That branch requires CSP 1.80-preview133, which you probably don't have yet.

**Comment by ZerdNerd** [comment]
Oh. It's not available as I see, so it has to wait then.
