### ISSUE TITLE
Spawning in/teleporting to pits causes car to spawn in the floor at Bahrain.

### ISSUE THREAD

**Issue by choso143** [ac-sim-improvement-mods/ac-rules-and-race-enhancements#45]
I’m not really sure why this is happening, but it only happens when RARE is injected and only on specific tracks. It also doesn’t happen when spawning at the start line or hotlap start.

**Comment by WilliamGawlik** [comment]
I am testing this currently and do not see this issue. Which Bahrain track are you using?

**Comment by choso143** [comment]
Here’s the link: [https://www.racedepartment.com/downloads/bahrain-international-circuit-all-layouts.35001/](https://www.racedepartment.com/downloads/bahrain-international-circuit-all-layouts.35001/)

**Comment by WilliamGawlik** [comment]
Is this the only track that this occurs on?

**Comment by choso143** [comment]
It doesn’t happen on any of the Kunos tracks. I’ve also tested it on the Vegas F1 circuit and Suzuka (both mods), and it doesn’t happen.

**Comment by WilliamGawlik** [comment]
Seems like this is not an issue I will investigate any further myself, due to it's isolated nature.
